{"uuid": "bfe4d5f6-cf01-40ca-8555-3ab1bf3ad11f", "children": ["25dedf56-1a6c-4baa-a12c-09824998d0ad"], "befores": [{"name": "broswer", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:9222\nfrom session not created: This version of ChromeDriver only supports Chrome version 96\nCurrent browser version is 98.0.4758.102\nStacktrace:\nBacktrace:\n\tOrdinal0 [0x003465C3+2516419]\n\tOrdinal0 [0x002DFAA1+2095777]\n\tOrdinal0 [0x001E2698+1058456]\n\tOrdinal0 [0x002009DD+1182173]\n\tOrdinal0 [0x001FA23B+1155643]\n\tOrdinal0 [0x001FA021+1155105]\n\tOrdinal0 [0x0022A90F+1353999]\n\tOrdinal0 [0x0022A57A+1353082]\n\tOrdinal0 [0x0022620B+1335819]\n\tOrdinal0 [0x002025E7+1189351]\n\tOrdinal0 [0x00203449+1193033]\n\tGetHandleVerifier [0x004D3AA4+1573796]\n\tGetHandleVerifier [0x0057D8E7+2269671]\n\tGetHandleVerifier [0x003D491B+528923]\n\tGetHandleVerifier [0x003D3D69+525929]\n\tOrdinal0 [0x002E50A9+2117801]\n\tOrdinal0 [0x002E9458+2135128]\n\tOrdinal0 [0x002E9592+2135442]\n\tOrdinal0 [0x002F30F1+2175217]\n\tBaseThreadInitThunk [0x75EAFA29+25]\n\tRtlGetAppContainerNamedObjectPath [0x77807A9E+286]\n\tRtlGetAppContainerNamedObjectPath [0x77807A6E+238]\n\t(No symbol) [0x00000000]\n\n", "trace": "  File \"C:\\Python\\Python310\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"C:\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 1126, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"C:\\Python\\Python310\\lib\\site-packages\\_pytest\\fixtures.py\", line 925, in call_fixture_func\n    fixture_result = next(generator)\n  File \"E:\\Pycharm Project\\pytest_taobao\\pytest_homework\\conftest.py\", line 23, in broswer\n    driver = webdriver.Chrome(options=options)  # options=options\n  File \"C:\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chrome\\webdriver.py\", line 70, in __init__\n    super(WebDriver, self).__init__(DesiredCapabilities.CHROME['browserName'], \"goog\",\n  File \"C:\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\chromium\\webdriver.py\", line 93, in __init__\n    RemoteWebDriver.__init__(\n  File \"C:\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 268, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"C:\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 359, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"C:\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 424, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Python\\Python310\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 247, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1645425221212, "stop": 1645425225781}], "start": 1645425221212, "stop": 1645425225875}